# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
SCHEME = 'RFTestDemo'
APP_NAME = 'RFTestDemo' 
PROJECT_FILE_PATH = './RFTestDemo.xcodeproj'
# WORKSPECE_FILE_PATH = 'RFTestDemo.xcworkspace'

platform :ios do
  before_all do |lane, options|
  # git_pull
  cocoapods(
    clean: true,
    podfile: "./Podfile"
  )
  end

	desc "this is a test lane"
	lane :tests do
		run_tests(scheme: "#{SCHEME}",
				      devices:["iPhone 8"])
	end

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "====>this is beta lane"
  lane :beta do 
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
  	build_app(scheme: "#{SCHEME}",
  			      include_bitcode: true,
              export_xcargs: "-allowProvisioningUpdates",
              export_method: "development")
    pilot
  end
  desc "企业版"
  lane :inHouse do
    get_certificates
    get_provisioning_profile
    build_app(
       workspace: "#{SCHEME}.xcworkspace",
       configuration: "Release",
       scheme: "#{SCHEME}",
       silent: true,
       clean: true,
       export_method:"enterprise",
       output_directory: "./build", # 打包后的 ipa 文件存放的目录
       output_name:"inHouse.ipa")  # ipa 文件名
    
  end
  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    build_app(scheme: "#{SCHEME}") # Build your app - more options available
    deliver(force: true)
    # frameit
  
  end
end
